/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChartList: typeof import('./src/components/chartList/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserModal: typeof import('./src/components/userModal/index.vue')['default']
    VarAvatar: typeof import('@varlet/ui')['_AvatarComponent']
    VarBadge: typeof import('@varlet/ui')['_BadgeComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCol: typeof import('@varlet/ui')['_ColComponent']
    VarDivider: typeof import('@varlet/ui')['_DividerComponent']
    VarEllipsis: typeof import('@varlet/ui')['_EllipsisComponent']
    VarForm: typeof import('@varlet/ui')['_FormComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarImagePreview: typeof import('@varlet/ui')['_ImagePreviewComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarPopup: typeof import('@varlet/ui')['_PopupComponent']
    VarRadio: typeof import('@varlet/ui')['_RadioComponent']
    VarRadioGroup: (typeof import('@varlet/ui'))['_RadioGroupComponent']
    VarRow: typeof import('@varlet/ui')['_RowComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
    VarSwitch: typeof import('@varlet/ui')['_SwitchComponent']
    VarTab: typeof import('@varlet/ui')['_TabComponent']
    VarTabItem: typeof import('@varlet/ui')['_TabItemComponent']
    VarTabs: typeof import('@varlet/ui')['_TabsComponent']
    VarTabsItems: typeof import('@varlet/ui')['_TabsItemsComponent']
    VarTooltip: typeof import('@varlet/ui')['_TooltipComponent']
  }
  export interface ComponentCustomProperties {
    vHover: typeof import('@varlet/ui')['_HoverComponent']
  }
}
