/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChartList: typeof import('./src/components/chartList/index.vue')['default']
    EmojiPicker: typeof import('./src/components/emojiPicker/index.vue')['default']
    FriendList: typeof import('./src/components/friendList/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserModal: typeof import('./src/components/userModal/index.vue')['default']
    VarAvatar: typeof import('@varlet/ui')['_AvatarComponent']
    VarBadge: typeof import('@varlet/ui')['_BadgeComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarCol: typeof import('@varlet/ui')['_ColComponent']
    VarCollapseTransition: typeof import('@varlet/ui')['_CollapseTransitionComponent']
    VarDivider: typeof import('@varlet/ui')['_DividerComponent']
    VarEllipsis: typeof import('@varlet/ui')['_EllipsisComponent']
    VarForm: typeof import('@varlet/ui')['_FormComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarImagePreview: typeof import('@varlet/ui')['_ImagePreviewComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarMenu: typeof import('@varlet/ui')['_MenuComponent']
    VarOption: typeof import('@varlet/ui')['_OptionComponent']
    VarPopup: typeof import('@varlet/ui')['_PopupComponent']
    VarRadio: typeof import('@varlet/ui')['_RadioComponent']
    VarRow: typeof import('@varlet/ui')['_RowComponent']
    VarSelect: typeof import('@varlet/ui')['_SelectComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
    VarStyleProvider: typeof import('@varlet/ui')['_StyleProviderComponent']
    VarSwitch: typeof import('@varlet/ui')['_SwitchComponent']
    VarTooltip: typeof import('@varlet/ui')['_TooltipComponent']
  }
  export interface ComponentCustomProperties {
    vHover: typeof import('@varlet/ui')['_HoverComponent']
  }
}
